### ISSUE TITLE
Two processes are created if the video is in a second activity

### ISSUE THREAD

**Issue by RamonJSanchez** [googlesamples/android-PictureInPicture#2]
If you change the video player to a secondary activity and you enter in PictureinPicture mode a new process is created.
This is really easy to reproduce by adding a new activity as MAIN and LAUNCHER with a button that just launches the current MainActivity (with the player) and enter in PiP mode, the Main activity will be left being displayed and you can navigate to other activities (if available).

If you press the video (in PiP mode) twice to open the activity again you will get the two processes.

![twoprocesses](https://user-images.githubusercontent.com/23748327/28806089-eb158bce-7622-11e7-8ee9-aff8af2bc16e.png)

**Comment by benbaxter** [comment]
This is working as intended. We published an article about how the framework operates underneath and what developers should do. 

https://medium.com/google-developers/navigation-patterns-with-pip-2c5b6a446ba0
