### ISSUE TITLE
"(No title program)" shown on Android TV 8.0 when app is in PiP mode

### ISSUE THREAD

**Issue by alexeyvasilyev** [googlesamples/android-PictureInPicture#4]
![screenshot_1503395238](https://user-images.githubusercontent.com/963292/29559708-81721922-8738-11e7-8d33-d1d63fac7f26.png)

App name should be shown instead of "(No title program)".

**Comment by anthonymonori** [comment]
I'm facing the same issue and just posted a question on StackOverflow: https://stackoverflow.com/questions/47219596/how-to-set-the-icon-and-title-on-android-tv-home-screen-for-the-currently-runnin

**Comment by benbaxter** [comment]
@alexeyvasilyev @anthonymonori 
This has been resolved with the latest commit. Thanks for filing the issue!
